/* AUTO-GENERATED from can_protocol.yaml — DO NOT EDIT */
/* Generated on: 2026-07-20 11:45:26 */

#ifndef CAN_PROTOCOL_GENERATED_H
#define CAN_PROTOCOL_GENERATED_H

/* Protocol Version */
#define CAN_PROTOCOL_VERSION 1U
#define CAN_PROTOCOL_PAYLOAD_SIZE 8U

/* CAN Identifiers */
#define CAN_PROTOCOL_GUI_COMMAND_ID_EXT 0x1894AABBUL
#define CAN_PROTOCOL_RTC_STATUS_TX_ID 0x551U
#define CAN_PROTOCOL_RTC_TIME_TX_ID 0x556U
#define CAN_PROTOCOL_SYSTEM_STATUS_TX_ID 0x557U
#define CAN_PROTOCOL_RTC_ALARM_EVENT_TX_ID 0x558U

/* Slot Flags */
#define CAN_PROTOCOL_SLOT_FLAG_ENABLE 0x01U
#define CAN_PROTOCOL_SLOT_FLAG_EXTENDED_ID 0x02U

/* Alarm Enable Flags */
#define CAN_PROTOCOL_RTC_ALARM_ENABLE_SECOND 0x01U
#define CAN_PROTOCOL_RTC_ALARM_ENABLE_MINUTE 0x02U
#define CAN_PROTOCOL_RTC_ALARM_ENABLE_HOUR 0x04U
#define CAN_PROTOCOL_RTC_ALARM_ENABLE_DAY 0x08U
#define CAN_PROTOCOL_RTC_ALARM_ENABLE_WEEKDAY 0x10U
#define CAN_PROTOCOL_RTC_ALARM_ENABLE_MASK 0x1FU

/* Alarm Event Flags */
#define CAN_PROTOCOL_RTC_ALARM_EVENT_AF 0x01U
#define CAN_PROTOCOL_RTC_ALARM_EVENT_AIE 0x02U
#define CAN_PROTOCOL_RTC_ALARM_EVENT_CONFIG_OK 0x04U

/* Command Codes */
typedef enum
{
    CAN_PROTOCOL_CMD_SET_SLOT_1 = 0x01U,
    CAN_PROTOCOL_CMD_SET_SLOT_2 = 0x02U,
    CAN_PROTOCOL_CMD_LED_CONTROL = 0x10U,
    CAN_PROTOCOL_CMD_START_SLOT_1_COUNTER = 0x11U,
    CAN_PROTOCOL_CMD_START_SLOT_2_COUNTER = 0x12U,
    CAN_PROTOCOL_CMD_RTC_SET_TIME = 0x20U,
    CAN_PROTOCOL_CMD_RTC_SET_DATETIME = 0x21U,
    CAN_PROTOCOL_CMD_RTC_SET_ALARM = 0x22U
} CAN_Protocol_Command_t;

/* RTC Status Codes */
typedef enum
{
    CAN_PROTOCOL_RTC_STATUS_INIT_OK = 0xA1U,
    CAN_PROTOCOL_RTC_STATUS_WRITE_VERIFY_OK = 0xA2U,
    CAN_PROTOCOL_RTC_STATUS_RECONNECTED = 0xA3U,
    CAN_PROTOCOL_RTC_STATUS_ALARM_WRITE_VERIFY_OK = 0xA4U,
    CAN_PROTOCOL_RTC_STATUS_INIT_FAILED = 0xE1U,
    CAN_PROTOCOL_RTC_STATUS_READ_FAILED = 0xE2U,
    CAN_PROTOCOL_RTC_STATUS_INVALID_DATETIME = 0xE4U,
    CAN_PROTOCOL_RTC_STATUS_CONTROL_READ_FAILED = 0xE5U,
    CAN_PROTOCOL_RTC_STATUS_STOP_WRITE_FAILED = 0xE6U,
    CAN_PROTOCOL_RTC_STATUS_CPR_WRITE_FAILED = 0xE7U,
    CAN_PROTOCOL_RTC_STATUS_CALENDAR_WRITE_FAILED = 0xE8U,
    CAN_PROTOCOL_RTC_STATUS_START_WRITE_FAILED = 0xE9U,
    CAN_PROTOCOL_RTC_STATUS_RECOVERY_FAILED = 0xEAU,
    CAN_PROTOCOL_RTC_STATUS_BUSY = 0xEBU,
    CAN_PROTOCOL_RTC_STATUS_ALARM_NOT_READY = 0xECU,
    CAN_PROTOCOL_RTC_STATUS_INVALID_ALARM_CONFIG = 0xEDU,
    CAN_PROTOCOL_RTC_STATUS_ALARM_WRITE_FAILED = 0xEEU,
    CAN_PROTOCOL_RTC_STATUS_ALARM_READBACK_FAILED = 0xEFU,
    CAN_PROTOCOL_RTC_STATUS_ALARM_VERIFY_MISMATCH = 0xF0U,
    CAN_PROTOCOL_RTC_STATUS_ALARM_FLAG_CLEAR_FAILED = 0xF1U
} CAN_Protocol_RtcStatusCode_t;

/* RTC Alarm Event Codes */
typedef enum
{
    CAN_PROTOCOL_RTC_ALARM_EVENT_TRIGGERED = 0x01U
} CAN_Protocol_RtcAlarmEventCode_t;

#endif /* CAN_PROTOCOL_GENERATED_H */
