/* AUTO-GENERATED from can_protocol.yaml — DO NOT EDIT */

#ifndef CAN_PROTOCOL_GENERATED_H
#define CAN_PROTOCOL_GENERATED_H

/* Protocol Version */
#define CAN_PROTOCOL_VERSION 1U
#define CAN_PROTOCOL_PAYLOAD_SIZE 8U

/* CAN Identifiers */
#define CAN_PROTOCOL_GUI_COMMAND_ID_EXT 0x1894AABBUL
#define CAN_PROTOCOL_RTC_STATUS_TX_ID 0x551U
#define CAN_PROTOCOL_RTC_TIME_TX_ID 0x556U
#define CAN_PROTOCOL_SYSTEM_STATUS_TX_ID 0x557U
#define CAN_PROTOCOL_RTC_ALARM_EVENT_TX_ID 0x558U
#define CAN_PROTOCOL_PWM_STATUS_TX_ID 0x55CU
#define CAN_PROTOCOL_INPUT_CAPTURE_STATUS_TX_ID 0x55DU
#define CAN_PROTOCOL_PWM_SELF_TEST_STATUS_TX_ID 0x55EU
#define CAN_PROTOCOL_PWM_SELF_TEST_RESULT_TX_ID 0x55FU
#define CAN_PROTOCOL_LOG_RESPONSE_TX_ID 0x55AU
#define CAN_PROTOCOL_LOG_HEARTBEAT_TX_ID 0x55BU
#define CAN_PROTOCOL_COMMAND_ACK_TX_ID 0x550U

/* Reliable Command Transport */
#define CAN_PROTOCOL_GUI_COMMAND_SEQUENCE_MASK 0x000000FFUL
#define CAN_PROTOCOL_GUI_COMMAND_SESSION_MASK 0x0000FF00UL
#define CAN_PROTOCOL_GUI_COMMAND_SESSION_SHIFT 8U
#define CAN_PROTOCOL_GUI_COMMAND_ID_MASK_EXT 0x1FFF0000UL

/* Slot Flags */
#define CAN_PROTOCOL_SLOT_FLAG_ENABLE 0x01U
#define CAN_PROTOCOL_SLOT_FLAG_EXTENDED_ID 0x02U

/* Alarm Enable Flags */
#define CAN_PROTOCOL_RTC_ALARM_ENABLE_SECOND 0x01U
#define CAN_PROTOCOL_RTC_ALARM_ENABLE_MINUTE 0x02U
#define CAN_PROTOCOL_RTC_ALARM_ENABLE_HOUR 0x04U
#define CAN_PROTOCOL_RTC_ALARM_ENABLE_DAY 0x08U
#define CAN_PROTOCOL_RTC_ALARM_ENABLE_WEEKDAY 0x10U
#define CAN_PROTOCOL_RTC_ALARM_ENABLE_MASK 0x1FU

/* Alarm Event Flags */
#define CAN_PROTOCOL_RTC_ALARM_EVENT_AF 0x01U
#define CAN_PROTOCOL_RTC_ALARM_EVENT_AIE 0x02U
#define CAN_PROTOCOL_RTC_ALARM_EVENT_CONFIG_OK 0x04U

/* Command Codes */
typedef enum
{
    CAN_PROTOCOL_CMD_SET_SLOT_1 = 0x01U,
    CAN_PROTOCOL_CMD_SET_SLOT_2 = 0x02U,
    CAN_PROTOCOL_CMD_LED_CONTROL = 0x10U,
    CAN_PROTOCOL_CMD_START_SLOT_1_COUNTER = 0x11U,
    CAN_PROTOCOL_CMD_START_SLOT_2_COUNTER = 0x12U,
    CAN_PROTOCOL_CMD_RTC_SET_TIME = 0x20U,
    CAN_PROTOCOL_CMD_RTC_SET_DATETIME = 0x21U,
    CAN_PROTOCOL_CMD_RTC_SET_ALARM = 0x22U,
    CAN_PROTOCOL_CMD_PWM_SET = 0x40U,
    CAN_PROTOCOL_CMD_PWM_SELF_TEST = 0x41U,
    CAN_PROTOCOL_CMD_LOG_GET_INFO = 0x30U,
    CAN_PROTOCOL_CMD_LOG_READ_SEQUENCE = 0x31U,
    CAN_PROTOCOL_CMD_SESSION_START = 0x7EU
} CAN_Protocol_Command_t;

/* Command Acknowledgement Status Codes */
typedef enum
{
    CAN_PROTOCOL_COMMAND_ACK_ACCEPTED = 0x00U,
    CAN_PROTOCOL_COMMAND_ACK_DUPLICATE = 0x01U,
    CAN_PROTOCOL_COMMAND_ACK_INVALID_PAYLOAD = 0x02U,
    CAN_PROTOCOL_COMMAND_ACK_UNKNOWN_COMMAND = 0x03U,
    CAN_PROTOCOL_COMMAND_ACK_ACCESS_DENIED = 0x04U,
    CAN_PROTOCOL_COMMAND_ACK_REPLAY_REJECTED = 0x05U,
    CAN_PROTOCOL_COMMAND_ACK_SESSION_REQUIRED = 0x06U,
    CAN_PROTOCOL_COMMAND_ACK_PROTOCOL_MISMATCH = 0x07U
} CAN_Protocol_CommandAckStatus_t;

/* Command Acknowledgement Flags */
#define CAN_PROTOCOL_COMMAND_ACK_FLAG_EXECUTED 0x01U
#define CAN_PROTOCOL_COMMAND_ACK_FLAG_ACCESS_OPEN 0x02U
#define CAN_PROTOCOL_COMMAND_ACK_FLAG_SESSION_STARTED 0x04U

/* RTC Status Codes */
typedef enum
{
    CAN_PROTOCOL_RTC_STATUS_INIT_OK = 0xA1U,
    CAN_PROTOCOL_RTC_STATUS_WRITE_VERIFY_OK = 0xA2U,
    CAN_PROTOCOL_RTC_STATUS_RECONNECTED = 0xA3U,
    CAN_PROTOCOL_RTC_STATUS_ALARM_WRITE_VERIFY_OK = 0xA4U,
    CAN_PROTOCOL_RTC_STATUS_INIT_FAILED = 0xE1U,
    CAN_PROTOCOL_RTC_STATUS_READ_FAILED = 0xE2U,
    CAN_PROTOCOL_RTC_STATUS_INVALID_DATETIME = 0xE4U,
    CAN_PROTOCOL_RTC_STATUS_CONTROL_READ_FAILED = 0xE5U,
    CAN_PROTOCOL_RTC_STATUS_STOP_WRITE_FAILED = 0xE6U,
    CAN_PROTOCOL_RTC_STATUS_CPR_WRITE_FAILED = 0xE7U,
    CAN_PROTOCOL_RTC_STATUS_CALENDAR_WRITE_FAILED = 0xE8U,
    CAN_PROTOCOL_RTC_STATUS_START_WRITE_FAILED = 0xE9U,
    CAN_PROTOCOL_RTC_STATUS_RECOVERY_FAILED = 0xEAU,
    CAN_PROTOCOL_RTC_STATUS_BUSY = 0xEBU,
    CAN_PROTOCOL_RTC_STATUS_ALARM_NOT_READY = 0xECU,
    CAN_PROTOCOL_RTC_STATUS_INVALID_ALARM_CONFIG = 0xEDU,
    CAN_PROTOCOL_RTC_STATUS_ALARM_WRITE_FAILED = 0xEEU,
    CAN_PROTOCOL_RTC_STATUS_ALARM_READBACK_FAILED = 0xEFU,
    CAN_PROTOCOL_RTC_STATUS_ALARM_VERIFY_MISMATCH = 0xF0U,
    CAN_PROTOCOL_RTC_STATUS_ALARM_FLAG_CLEAR_FAILED = 0xF1U
} CAN_Protocol_RtcStatusCode_t;

/* RTC Alarm Event Codes */
typedef enum
{
    CAN_PROTOCOL_RTC_ALARM_EVENT_TRIGGERED = 0x01U
} CAN_Protocol_RtcAlarmEventCode_t;

#endif /* CAN_PROTOCOL_GENERATED_H */
