/* AUTO-GENERATED from can_protocol.yaml — DO NOT EDIT */

#ifndef CAN_PROTOCOL_GENERATED_H
#define CAN_PROTOCOL_GENERATED_H

/* Protocol Version */
#define CAN_PROTOCOL_VERSION 2U
#define CAN_PROTOCOL_PAYLOAD_SIZE 8U

/* CAN Identifiers */
#define CAN_PROTOCOL_GUI_COMMAND_ID_EXT 0x1894AABBUL
#define CAN_PROTOCOL_RTC_STATUS_TX_ID 0x551U
#define CAN_PROTOCOL_RTC_TIME_TX_ID 0x556U
#define CAN_PROTOCOL_SYSTEM_STATUS_TX_ID 0x557U
#define CAN_PROTOCOL_RTC_ALARM_EVENT_TX_ID 0x558U
#define CAN_PROTOCOL_PWM_STATUS_TX_ID 0x55CU
#define CAN_PROTOCOL_INPUT_CAPTURE_STATUS_TX_ID 0x55DU
#define CAN_PROTOCOL_PWM_SELF_TEST_STATUS_TX_ID 0x55EU
#define CAN_PROTOCOL_PWM_SELF_TEST_RESULT_TX_ID 0x55FU
#define CAN_PROTOCOL_LOG_RESPONSE_TX_ID 0x55AU
#define CAN_PROTOCOL_LOG_HEARTBEAT_TX_ID 0x55BU
#define CAN_PROTOCOL_COMMAND_ACK_TX_ID 0x550U
#define CAN_PROTOCOL_TIC12400_STATUS_TX_ID 0x552U
#define CAN_PROTOCOL_TIC12400_SWITCH_STATE_TX_ID 0x554U
#define CAN_PROTOCOL_TIC12400_PROFILE_TX_ID 0x555U
#define CAN_PROTOCOL_CAN_RX_HEALTH_TX_ID 0x560U
#define CAN_PROTOCOL_TIMING_SERVICE_TX_ID 0x561U
#define CAN_PROTOCOL_TIMING_ACK_LATENCY_TX_ID 0x562U

/* Slot Flags */
#define CAN_PROTOCOL_SLOT_FLAG_ENABLE 0x01U
#define CAN_PROTOCOL_SLOT_FLAG_EXTENDED_ID 0x02U

/* System Status Control Policy */
#define CAN_PROTOCOL_SYSTEM_REQUEST_SLOT_1 0x01U
#define CAN_PROTOCOL_SYSTEM_REQUEST_SLOT_2 0x02U
#define CAN_PROTOCOL_SYSTEM_REQUEST_LED_1 0x04U
#define CAN_PROTOCOL_SYSTEM_REQUEST_LED_2 0x08U
#define CAN_PROTOCOL_SYSTEM_REQUEST_PWM 0x10U
#define CAN_PROTOCOL_SYSTEM_PHYSICAL_DATA_VALID 0x01U
#define CAN_PROTOCOL_SYSTEM_PHYSICAL_IN0_CLOSED 0x02U
#define CAN_PROTOCOL_SYSTEM_PHYSICAL_IN1_CLOSED 0x04U
#define CAN_PROTOCOL_SYSTEM_PHYSICAL_IN2_CLOSED 0x08U
#define CAN_PROTOCOL_SYSTEM_PHYSICAL_IN3_CLOSED 0x10U
#define CAN_PROTOCOL_SYSTEM_OVERRIDE_SLOT_1_BLOCKED 0x01U
#define CAN_PROTOCOL_SYSTEM_OVERRIDE_SLOT_2_BLOCKED 0x02U
#define CAN_PROTOCOL_SYSTEM_OVERRIDE_LED_1_OVERRIDDEN 0x04U
#define CAN_PROTOCOL_SYSTEM_OVERRIDE_PWM_BLOCKED 0x10U
#define CAN_PROTOCOL_PWM_CONTROL_REQUESTED 0x01U
#define CAN_PROTOCOL_PWM_CONTROL_PHYSICAL_PERMITTED 0x02U
#define CAN_PROTOCOL_PWM_CONTROL_BLOCKED 0x04U
#define CAN_PROTOCOL_PWM_CONTROL_SWITCH_DATA_VALID 0x08U
#define CAN_PROTOCOL_CAN_RX_HEALTH_WATERMARK_SEEN 0x01U
#define CAN_PROTOCOL_CAN_RX_HEALTH_FIFO_FULL_SEEN 0x02U
#define CAN_PROTOCOL_CAN_RX_HEALTH_MESSAGE_LOST 0x04U
#define CAN_PROTOCOL_CAN_RX_HEALTH_BUDGET_EXHAUSTED 0x08U
#define CAN_PROTOCOL_CAN_RX_HEALTH_HAL_ERROR 0x10U
#define CAN_PROTOCOL_TIMING_SERVICE_ENABLED 0x01U
#define CAN_PROTOCOL_TIMING_SERVICE_CURRENT_OVERRUN 0x02U
#define CAN_PROTOCOL_TIMING_SERVICE_OVERRUN_LATCHED 0x04U

/* PWM Self-Test State Codes */
#define CAN_PROTOCOL_PWM_SELF_TEST_STATE_IDLE 0U
#define CAN_PROTOCOL_PWM_SELF_TEST_STATE_RUNNING 1U
#define CAN_PROTOCOL_PWM_SELF_TEST_STATE_PASSED 2U
#define CAN_PROTOCOL_PWM_SELF_TEST_STATE_FAILED 3U
#define CAN_PROTOCOL_PWM_SELF_TEST_STATE_CANCELLED 4U
#define CAN_PROTOCOL_PWM_SELF_TEST_STATE_ERROR 5U

/* Alarm Enable Flags */
#define CAN_PROTOCOL_RTC_ALARM_ENABLE_SECOND 0x01U
#define CAN_PROTOCOL_RTC_ALARM_ENABLE_MINUTE 0x02U
#define CAN_PROTOCOL_RTC_ALARM_ENABLE_HOUR 0x04U
#define CAN_PROTOCOL_RTC_ALARM_ENABLE_DAY 0x08U
#define CAN_PROTOCOL_RTC_ALARM_ENABLE_WEEKDAY 0x10U
#define CAN_PROTOCOL_RTC_ALARM_ENABLE_MASK 0x1FU

/* Alarm Event Flags */
#define CAN_PROTOCOL_RTC_ALARM_EVENT_AF 0x01U
#define CAN_PROTOCOL_RTC_ALARM_EVENT_AIE 0x02U
#define CAN_PROTOCOL_RTC_ALARM_EVENT_CONFIG_OK 0x04U

/* TIC12400 Telemetry */
#define CAN_PROTOCOL_TIC12400_CHANNEL_COUNT 24U
#define CAN_PROTOCOL_TIC12400_BATTERY_CAPABLE_MASK 0x0003FFUL
#define CAN_PROTOCOL_TIC12400_SWITCH_DATA_VALID 0x01U
#define CAN_PROTOCOL_TIC12400_PROFILE_CONFIGURATION_VALID 0x01U
#define CAN_PROTOCOL_TIC12400_STATUS_ONLINE 0x01U
#define CAN_PROTOCOL_TIC12400_STATUS_CONFIGURATION_VALID 0x02U
#define CAN_PROTOCOL_TIC12400_STATUS_CRC_COMPLETE 0x04U
#define CAN_PROTOCOL_TIC12400_STATUS_MONITORING 0x08U
#define CAN_PROTOCOL_TIC12400_STATUS_POR_OBSERVED 0x20U
#define CAN_PROTOCOL_TIC12400_STATUS_SERVICE_FAULT 0x40U
#define CAN_PROTOCOL_TIC12400_TRANSACTION_SPI_FAIL 0x01U
#define CAN_PROTOCOL_TIC12400_TRANSACTION_PARITY_FAIL 0x02U
#define CAN_PROTOCOL_TIC12400_TRANSACTION_SWITCH_STATE_CHANGE 0x04U
#define CAN_PROTOCOL_TIC12400_TRANSACTION_SUPPLY_THRESHOLD 0x08U
#define CAN_PROTOCOL_TIC12400_TRANSACTION_TEMPERATURE 0x10U
#define CAN_PROTOCOL_TIC12400_TRANSACTION_OTHER_INTERRUPT 0x20U
#define CAN_PROTOCOL_TIC12400_TRANSACTION_POWER_ON_RESET 0x40U
#define CAN_PROTOCOL_TIC12400_RESULT_OK 0x00U
#define CAN_PROTOCOL_TIC12400_RESULT_INVALID_ARGUMENT 0x01U
#define CAN_PROTOCOL_TIC12400_RESULT_INVALID_ADDRESS 0x02U
#define CAN_PROTOCOL_TIC12400_RESULT_HAL_ERROR 0x03U
#define CAN_PROTOCOL_TIC12400_RESULT_RESPONSE_PARITY_ERROR 0x04U
#define CAN_PROTOCOL_TIC12400_RESULT_DEVICE_SPI_ERROR 0x05U
#define CAN_PROTOCOL_TIC12400_RESULT_DEVICE_PARITY_ERROR 0x06U
#define CAN_PROTOCOL_TIC12400_RESULT_DEVICE_ID_MISMATCH 0x07U
#define CAN_PROTOCOL_TIC12400_RESULT_INVALID_DATA 0x08U
#define CAN_PROTOCOL_TIC12400_RESULT_REGISTER_VERIFY_MISMATCH 0x09U
#define CAN_PROTOCOL_TIC12400_RESULT_CRC_TIMEOUT 0x0AU
#define CAN_PROTOCOL_TIC12400_RESULT_CRC_COMPLETION_MISSING 0x0BU
#define CAN_PROTOCOL_TIC12400_RESULT_UNKNOWN 0xFFU

/* Command Codes */
typedef enum
{
    CAN_PROTOCOL_CMD_SET_SLOT_1 = 0x01U,
    CAN_PROTOCOL_CMD_SET_SLOT_2 = 0x02U,
    CAN_PROTOCOL_CMD_LED_CONTROL = 0x10U,
    CAN_PROTOCOL_CMD_START_SLOT_1_COUNTER = 0x11U,
    CAN_PROTOCOL_CMD_START_SLOT_2_COUNTER = 0x12U,
    CAN_PROTOCOL_CMD_RTC_SET_TIME = 0x20U,
    CAN_PROTOCOL_CMD_RTC_SET_DATETIME = 0x21U,
    CAN_PROTOCOL_CMD_RTC_SET_ALARM = 0x22U,
    CAN_PROTOCOL_CMD_PWM_SET = 0x40U,
    CAN_PROTOCOL_CMD_PWM_SELF_TEST = 0x41U,
    CAN_PROTOCOL_CMD_LOG_GET_INFO = 0x30U,
    CAN_PROTOCOL_CMD_LOG_READ_SEQUENCE = 0x31U,
    CAN_PROTOCOL_CMD_TIC12400_SET_POLARITY = 0x50U
} CAN_Protocol_Command_t;

/* Command Acknowledgement Status Codes */
typedef enum
{
    CAN_PROTOCOL_COMMAND_ACK_ACCEPTED = 0x00U,
    CAN_PROTOCOL_COMMAND_ACK_INVALID_PAYLOAD = 0x02U,
    CAN_PROTOCOL_COMMAND_ACK_UNKNOWN_COMMAND = 0x03U,
    CAN_PROTOCOL_COMMAND_ACK_ACCESS_DENIED = 0x04U
} CAN_Protocol_CommandAckStatus_t;

/* Command Acknowledgement Flags */
#define CAN_PROTOCOL_COMMAND_ACK_FLAG_EXECUTED 0x01U
#define CAN_PROTOCOL_COMMAND_ACK_FLAG_ACCESS_OPEN 0x02U

/* RTC Status Codes */
typedef enum
{
    CAN_PROTOCOL_RTC_STATUS_INIT_OK = 0xA1U,
    CAN_PROTOCOL_RTC_STATUS_WRITE_VERIFY_OK = 0xA2U,
    CAN_PROTOCOL_RTC_STATUS_RECONNECTED = 0xA3U,
    CAN_PROTOCOL_RTC_STATUS_ALARM_WRITE_VERIFY_OK = 0xA4U,
    CAN_PROTOCOL_RTC_STATUS_INIT_FAILED = 0xE1U,
    CAN_PROTOCOL_RTC_STATUS_READ_FAILED = 0xE2U,
    CAN_PROTOCOL_RTC_STATUS_INVALID_DATETIME = 0xE4U,
    CAN_PROTOCOL_RTC_STATUS_CONTROL_READ_FAILED = 0xE5U,
    CAN_PROTOCOL_RTC_STATUS_STOP_WRITE_FAILED = 0xE6U,
    CAN_PROTOCOL_RTC_STATUS_CPR_WRITE_FAILED = 0xE7U,
    CAN_PROTOCOL_RTC_STATUS_CALENDAR_WRITE_FAILED = 0xE8U,
    CAN_PROTOCOL_RTC_STATUS_START_WRITE_FAILED = 0xE9U,
    CAN_PROTOCOL_RTC_STATUS_RECOVERY_FAILED = 0xEAU,
    CAN_PROTOCOL_RTC_STATUS_BUSY = 0xEBU,
    CAN_PROTOCOL_RTC_STATUS_ALARM_NOT_READY = 0xECU,
    CAN_PROTOCOL_RTC_STATUS_INVALID_ALARM_CONFIG = 0xEDU,
    CAN_PROTOCOL_RTC_STATUS_ALARM_WRITE_FAILED = 0xEEU,
    CAN_PROTOCOL_RTC_STATUS_ALARM_READBACK_FAILED = 0xEFU,
    CAN_PROTOCOL_RTC_STATUS_ALARM_VERIFY_MISMATCH = 0xF0U,
    CAN_PROTOCOL_RTC_STATUS_ALARM_FLAG_CLEAR_FAILED = 0xF1U,
    CAN_PROTOCOL_RTC_STATUS_WRITE_VERIFY_MISMATCH = 0xF2U
} CAN_Protocol_RtcStatusCode_t;

/* RTC Alarm Event Codes */
typedef enum
{
    CAN_PROTOCOL_RTC_ALARM_EVENT_TRIGGERED = 0x01U
} CAN_Protocol_RtcAlarmEventCode_t;

#endif /* CAN_PROTOCOL_GENERATED_H */
