# AUTO-GENERATED from can_protocol.yaml — DO NOT EDIT

PROTOCOL_VERSION = 1
PAYLOAD_SIZE = 8

# CAN Identifiers
GUI_COMMAND_ID_EXT = 0x1894AABB
RTC_STATUS_TX_ID = 0x551
RTC_TIME_TX_ID = 0x556
SYSTEM_STATUS_TX_ID = 0x557
RTC_ALARM_EVENT_TX_ID = 0x558
PWM_STATUS_TX_ID = 0x55C
INPUT_CAPTURE_STATUS_TX_ID = 0x55D
PWM_SELF_TEST_STATUS_TX_ID = 0x55E
PWM_SELF_TEST_RESULT_TX_ID = 0x55F
LOG_RESPONSE_TX_ID = 0x55A
LOG_HEARTBEAT_TX_ID = 0x55B
COMMAND_ACK_TX_ID = 0x550
TIC12400_STATUS_TX_ID = 0x552
TIC12400_ADC_TX_ID = 0x553
TIC12400_SWITCH_STATE_TX_ID = 0x554

# Reliable Command Transport
GUI_COMMAND_SEQUENCE_MASK = 0x000000FF
GUI_COMMAND_SESSION_MASK = 0x0000FF00
GUI_COMMAND_SESSION_SHIFT = 8
GUI_COMMAND_ID_MASK_EXT = 0x1FFF0000

# Command Codes
CMD_SET_SLOT_1 = 0x01
CMD_SET_SLOT_2 = 0x02
CMD_LED_CONTROL = 0x10
CMD_START_SLOT_1_COUNTER = 0x11
CMD_START_SLOT_2_COUNTER = 0x12
CMD_RTC_SET_TIME = 0x20
CMD_RTC_SET_DATETIME = 0x21
CMD_RTC_SET_ALARM = 0x22
CMD_PWM_SET = 0x40
CMD_PWM_SELF_TEST = 0x41
CMD_LOG_GET_INFO = 0x30
CMD_LOG_READ_SEQUENCE = 0x31
CMD_SESSION_START = 0x7E

# Command Acknowledgement Status Codes
COMMAND_ACK_ACCEPTED = 0x00
COMMAND_ACK_DUPLICATE = 0x01
COMMAND_ACK_INVALID_PAYLOAD = 0x02
COMMAND_ACK_UNKNOWN_COMMAND = 0x03
COMMAND_ACK_ACCESS_DENIED = 0x04
COMMAND_ACK_REPLAY_REJECTED = 0x05
COMMAND_ACK_SESSION_REQUIRED = 0x06
COMMAND_ACK_PROTOCOL_MISMATCH = 0x07

# Command Acknowledgement Flags
COMMAND_ACK_FLAG_EXECUTED = 0x01
COMMAND_ACK_FLAG_ACCESS_OPEN = 0x02
COMMAND_ACK_FLAG_SESSION_STARTED = 0x04

# Slot Flags
SLOT_FLAG_ENABLE = 0x01
SLOT_FLAG_EXTENDED_ID = 0x02

# System Status Control Policy
SYSTEM_REQUEST_SLOT_1 = 0x01
SYSTEM_REQUEST_SLOT_2 = 0x02
SYSTEM_REQUEST_LED_1 = 0x04
SYSTEM_REQUEST_LED_2 = 0x08
SYSTEM_REQUEST_PWM = 0x10
SYSTEM_PHYSICAL_DATA_VALID = 0x01
SYSTEM_PHYSICAL_IN0_CLOSED = 0x02
SYSTEM_PHYSICAL_IN1_CLOSED = 0x04
SYSTEM_PHYSICAL_IN2_CLOSED = 0x08
SYSTEM_PHYSICAL_IN3_CLOSED = 0x10
SYSTEM_OVERRIDE_SLOT_1_BLOCKED = 0x01
SYSTEM_OVERRIDE_SLOT_2_BLOCKED = 0x02
SYSTEM_OVERRIDE_LED_1_OVERRIDDEN = 0x04
SYSTEM_OVERRIDE_PWM_BLOCKED = 0x10
PWM_CONTROL_REQUESTED = 0x01
PWM_CONTROL_PHYSICAL_PERMITTED = 0x02
PWM_CONTROL_BLOCKED = 0x04
PWM_CONTROL_SWITCH_DATA_VALID = 0x08

# Alarm Enable Flags
RTC_ALARM_ENABLE_SECOND = 0x01
RTC_ALARM_ENABLE_MINUTE = 0x02
RTC_ALARM_ENABLE_HOUR = 0x04
RTC_ALARM_ENABLE_DAY = 0x08
RTC_ALARM_ENABLE_WEEKDAY = 0x10

# Alarm Event Flags
RTC_ALARM_EVENT_AF = 0x01
RTC_ALARM_EVENT_AIE = 0x02
RTC_ALARM_EVENT_CONFIG_OK = 0x04

# TIC12400 Telemetry
TIC12400_ADC_CHANNEL_COUNT = 24
TIC12400_ADC_CODES_PER_FRAME = 3
TIC12400_ADC_GROUP_COUNT = 8
TIC12400_ADC_CODE_MAX = 1023
TIC12400_SWITCH_CLOSED_MAX_ADC_CODE = 512
TIC12400_SWITCH_DEBOUNCE_SAMPLES = 3
TIC12400_SWITCH_DATA_VALID = 0x01
TIC12400_STATUS_ONLINE = 0x01
TIC12400_STATUS_CONFIGURATION_VALID = 0x02
TIC12400_STATUS_CRC_COMPLETE = 0x04
TIC12400_STATUS_MONITORING = 0x08
TIC12400_STATUS_ADC_CHARACTERIZATION = 0x10
TIC12400_STATUS_POR_OBSERVED = 0x20
TIC12400_STATUS_SERVICE_FAULT = 0x40
TIC12400_TRANSACTION_SPI_FAIL = 0x01
TIC12400_TRANSACTION_PARITY_FAIL = 0x02
TIC12400_TRANSACTION_SWITCH_STATE_CHANGE = 0x04
TIC12400_TRANSACTION_SUPPLY_THRESHOLD = 0x08
TIC12400_TRANSACTION_TEMPERATURE = 0x10
TIC12400_TRANSACTION_OTHER_INTERRUPT = 0x20
TIC12400_TRANSACTION_POWER_ON_RESET = 0x40
TIC12400_RESULT_NAMES = {
    0x00: 'OK',
    0x01: 'INVALID_ARGUMENT',
    0x02: 'INVALID_ADDRESS',
    0x03: 'HAL_ERROR',
    0x04: 'RESPONSE_PARITY_ERROR',
    0x05: 'DEVICE_SPI_ERROR',
    0x06: 'DEVICE_PARITY_ERROR',
    0x07: 'DEVICE_ID_MISMATCH',
    0x08: 'INVALID_DATA',
    0x09: 'REGISTER_VERIFY_MISMATCH',
    0x0A: 'CRC_TIMEOUT',
    0x0B: 'CRC_COMPLETION_MISSING',
    0xFF: 'UNKNOWN',
}

# RTC Status Definitions
RTC_STATUS_DEFINITIONS = {
    0xA1: ('INFO', 'INIT_OK', 'PCA2131 address probe acknowledged'),
    0xA2: ('INFO', 'WRITE_VERIFY_OK', 'Calendar write verified by readback'),
    0xA3: ('INFO', 'LINK_RECOVERED', 'I2C communication restored'),
    0xA4: ('INFO', 'ALARM_WRITE_VERIFY_OK', 'Alarm configuration verified by readback'),
    0xE1: ('FAULT', 'INIT_FAILED', 'PCA2131 not detected during initialization'),
    0xE2: ('FAULT', 'READ_FAILED', 'RTC register read failed'),
    0xE4: ('WARN', 'INVALID_DATETIME', 'Date/time parameters rejected'),
    0xE5: ('FAULT', 'CONTROL_READ_FAILED', 'Control_1 register read failed'),
    0xE6: ('FAULT', 'STOP_ASSERT_FAILED', 'STOP bit could not be asserted'),
    0xE7: ('FAULT', 'PRESCALER_RESET_FAILED', 'Prescaler reset command failed'),
    0xE8: ('FAULT', 'CALENDAR_WRITE_FAILED', 'Calendar register write failed'),
    0xE9: ('FAULT', 'STOP_RELEASE_FAILED', 'STOP bit could not be released'),
    0xEA: ('FAULT', 'RECOVERY_FAILED', 'RTC write recovery failed'),
    0xEB: ('WARN', 'BUSY', 'RTC operation already in progress'),
    0xEC: ('WARN', 'ALARM_NOT_READY', 'RTC is not ready for alarm configuration'),
    0xED: ('WARN', 'INVALID_ALARM_CONFIG', 'Alarm configuration was rejected'),
    0xEE: ('FAULT', 'ALARM_WRITE_FAILED', 'Alarm register write failed'),
    0xEF: ('FAULT', 'ALARM_READBACK_FAILED', 'Alarm register readback failed'),
    0xF0: ('FAULT', 'ALARM_VERIFY_MISMATCH', 'Alarm write/readback mismatch'),
    0xF1: ('FAULT', 'ALARM_FLAG_CLEAR_FAILED', 'Previous alarm flag could not be cleared'),
}

# RTC Communication Fault Codes
RTC_COMMUNICATION_FAULT_CODES = {
    0xE1, 0xE2, 0xE5, 0xE6, 0xE7, 0xE8, 0xE9, 0xEA
}

