# AUTO-GENERATED from can_protocol.yaml — DO NOT EDIT

PROTOCOL_VERSION = 2
PAYLOAD_SIZE = 8

# CAN Identifiers
GUI_COMMAND_ID_EXT = 0x1894AABB
DIAGNOSTIC_REQUEST_RX_ID = 0x7E0
DIAGNOSTIC_RESPONSE_TX_ID = 0x7E8
RTC_STATUS_TX_ID = 0x551
RTC_TIME_TX_ID = 0x556
SYSTEM_STATUS_TX_ID = 0x557
RTC_ALARM_EVENT_TX_ID = 0x558
PWM_STATUS_TX_ID = 0x55C
INPUT_CAPTURE_STATUS_TX_ID = 0x55D
PWM_SELF_TEST_STATUS_TX_ID = 0x55E
PWM_SELF_TEST_RESULT_TX_ID = 0x55F
LOG_RESPONSE_TX_ID = 0x55A
LOG_HEARTBEAT_TX_ID = 0x55B
COMMAND_ACK_TX_ID = 0x550
TIC12400_STATUS_TX_ID = 0x552
TIC12400_SWITCH_STATE_TX_ID = 0x554
TIC12400_PROFILE_TX_ID = 0x555
CAN_RX_HEALTH_TX_ID = 0x560
TIMING_SERVICE_TX_ID = 0x561
TIMING_ACK_LATENCY_TX_ID = 0x562

# Event Log Transport
LOG_VERSION = 1
LOG_RECORD_SIZE = 32
LOG_RAM_CAPACITY = 64
LOG_FRAGMENT_DATA_SIZE = 7
LOG_INFO_WIRE_SIZE = 18
LOG_INFO_FRAGMENT_COUNT = 3
LOG_RECORD_FRAGMENT_COUNT = 5
LOG_RECORD_MAGIC = 0x4C4F4731
LOG_COMMIT_MARKER = 0xA55A
LOG_INFO_FRAGMENT_BASE = 0x70
LOG_RECORD_FRAGMENT_BASE = 0x80
LOG_ERROR_FRAME = 0xF0
LOG_HEARTBEAT_FLAG_READY = 0x01
LOG_HEARTBEAT_FLAG_OVERWRITE = 0x02
LOG_ERROR_SEQUENCE_NOT_FOUND = 0x01

# Timing Service Codes
TIMING_SERVICE_NAMES = {
    0: 'MAIN_LOOP',
    1: 'TIC12400_PROBE',
    2: 'CONTROL',
    3: 'RTC',
    4: 'INPUT_CAPTURE',
    5: 'CAN_APP',
    6: 'TIC12400_CAN',
    7: 'WATCHDOG',
}

# Command Codes
CMD_SET_SLOT_1 = 0x01
CMD_SET_SLOT_2 = 0x02
CMD_LED_CONTROL = 0x10
CMD_START_SLOT_1_COUNTER = 0x11
CMD_START_SLOT_2_COUNTER = 0x12
CMD_RTC_SET_TIME = 0x20
CMD_RTC_SET_DATETIME = 0x21
CMD_RTC_SET_ALARM = 0x22
CMD_PWM_SET = 0x40
CMD_PWM_SELF_TEST = 0x41
CMD_LOG_GET_INFO = 0x30
CMD_LOG_READ_SEQUENCE = 0x31
CMD_TIC12400_SET_POLARITY = 0x50

# Command Acknowledgement Status Codes
COMMAND_ACK_ACCEPTED = 0x00
COMMAND_ACK_INVALID_PAYLOAD = 0x02
COMMAND_ACK_UNKNOWN_COMMAND = 0x03
COMMAND_ACK_ACCESS_DENIED = 0x04

# Command Acknowledgement Flags
COMMAND_ACK_FLAG_EXECUTED = 0x01
COMMAND_ACK_FLAG_ACCESS_OPEN = 0x02

# Slot Flags
SLOT_FLAG_ENABLE = 0x01
SLOT_FLAG_EXTENDED_ID = 0x02

# System Status Control Policy
SYSTEM_REQUEST_SLOT_1 = 0x01
SYSTEM_REQUEST_SLOT_2 = 0x02
SYSTEM_REQUEST_LED_1 = 0x04
SYSTEM_REQUEST_LED_2 = 0x08
SYSTEM_REQUEST_PWM = 0x10
SYSTEM_PHYSICAL_DATA_VALID = 0x01
SYSTEM_PHYSICAL_IN0_CLOSED = 0x02
SYSTEM_PHYSICAL_IN1_CLOSED = 0x04
SYSTEM_PHYSICAL_IN2_CLOSED = 0x08
SYSTEM_PHYSICAL_IN3_CLOSED = 0x10
SYSTEM_OVERRIDE_SLOT_1_BLOCKED = 0x01
SYSTEM_OVERRIDE_SLOT_2_BLOCKED = 0x02
SYSTEM_OVERRIDE_LED_1_OVERRIDDEN = 0x04
SYSTEM_OVERRIDE_PWM_BLOCKED = 0x10
PWM_CONTROL_REQUESTED = 0x01
PWM_CONTROL_PHYSICAL_PERMITTED = 0x02
PWM_CONTROL_BLOCKED = 0x04
PWM_CONTROL_SWITCH_DATA_VALID = 0x08
CAN_RX_HEALTH_WATERMARK_SEEN = 0x01
CAN_RX_HEALTH_FIFO_FULL_SEEN = 0x02
CAN_RX_HEALTH_MESSAGE_LOST = 0x04
CAN_RX_HEALTH_BUDGET_EXHAUSTED = 0x08
CAN_RX_HEALTH_HAL_ERROR = 0x10
TIMING_SERVICE_ENABLED = 0x01
TIMING_SERVICE_CURRENT_OVERRUN = 0x02
TIMING_SERVICE_OVERRUN_LATCHED = 0x04

# PWM Self-Test State Codes
PWM_SELF_TEST_STATE_NAMES = {
    0: 'Idle',
    1: 'Running',
    2: 'Passed',
    3: 'Failed',
    4: 'Cancelled',
    5: 'Firmware error',
}

# Alarm Enable Flags
RTC_ALARM_ENABLE_SECOND = 0x01
RTC_ALARM_ENABLE_MINUTE = 0x02
RTC_ALARM_ENABLE_HOUR = 0x04
RTC_ALARM_ENABLE_DAY = 0x08
RTC_ALARM_ENABLE_WEEKDAY = 0x10

# Alarm Event Flags
RTC_ALARM_EVENT_AF = 0x01
RTC_ALARM_EVENT_AIE = 0x02
RTC_ALARM_EVENT_CONFIG_OK = 0x04

# TIC12400 Telemetry
TIC12400_CHANNEL_COUNT = 24
TIC12400_BATTERY_CAPABLE_MASK = 0x0003FF
TIC12400_SWITCH_DATA_VALID = 0x01
TIC12400_PROFILE_CONFIGURATION_VALID = 0x01
TIC12400_STATUS_ONLINE = 0x01
TIC12400_STATUS_CONFIGURATION_VALID = 0x02
TIC12400_STATUS_CRC_COMPLETE = 0x04
TIC12400_STATUS_MONITORING = 0x08
TIC12400_STATUS_POR_OBSERVED = 0x20
TIC12400_STATUS_SERVICE_FAULT = 0x40
TIC12400_TRANSACTION_SPI_FAIL = 0x01
TIC12400_TRANSACTION_PARITY_FAIL = 0x02
TIC12400_TRANSACTION_SWITCH_STATE_CHANGE = 0x04
TIC12400_TRANSACTION_SUPPLY_THRESHOLD = 0x08
TIC12400_TRANSACTION_TEMPERATURE = 0x10
TIC12400_TRANSACTION_OTHER_INTERRUPT = 0x20
TIC12400_TRANSACTION_POWER_ON_RESET = 0x40
TIC12400_RESULT_NAMES = {
    0x00: 'OK',
    0x01: 'INVALID_ARGUMENT',
    0x02: 'INVALID_ADDRESS',
    0x03: 'HAL_ERROR',
    0x04: 'RESPONSE_PARITY_ERROR',
    0x05: 'DEVICE_SPI_ERROR',
    0x06: 'DEVICE_PARITY_ERROR',
    0x07: 'DEVICE_ID_MISMATCH',
    0x08: 'INVALID_DATA',
    0x09: 'REGISTER_VERIFY_MISMATCH',
    0x0A: 'CRC_TIMEOUT',
    0x0B: 'CRC_COMPLETION_MISSING',
    0xFF: 'UNKNOWN',
}

# RTC Status Definitions
RTC_STATUS_DEFINITIONS = {
    0xA1: ('INFO', 'INIT_OK', 'PCA2131 address probe acknowledged'),
    0xA2: ('INFO', 'WRITE_VERIFY_OK', 'Calendar write verified by readback'),
    0xA3: ('INFO', 'LINK_RECOVERED', 'I2C communication restored'),
    0xA4: ('INFO', 'ALARM_WRITE_VERIFY_OK', 'Alarm configuration verified by readback'),
    0xE1: ('FAULT', 'INIT_FAILED', 'PCA2131 not detected during initialization'),
    0xE2: ('FAULT', 'READ_FAILED', 'RTC register read failed'),
    0xE4: ('WARN', 'INVALID_DATETIME', 'Date/time parameters rejected'),
    0xE5: ('FAULT', 'CONTROL_READ_FAILED', 'Control_1 register read failed'),
    0xE6: ('FAULT', 'STOP_ASSERT_FAILED', 'STOP bit could not be asserted'),
    0xE7: ('FAULT', 'PRESCALER_RESET_FAILED', 'Prescaler reset command failed'),
    0xE8: ('FAULT', 'CALENDAR_WRITE_FAILED', 'Calendar register write failed'),
    0xE9: ('FAULT', 'STOP_RELEASE_FAILED', 'STOP bit could not be released'),
    0xEA: ('FAULT', 'RECOVERY_FAILED', 'RTC write recovery failed'),
    0xEB: ('WARN', 'BUSY', 'RTC operation already in progress'),
    0xEC: ('WARN', 'ALARM_NOT_READY', 'RTC is not ready for alarm configuration'),
    0xED: ('WARN', 'INVALID_ALARM_CONFIG', 'Alarm configuration was rejected'),
    0xEE: ('FAULT', 'ALARM_WRITE_FAILED', 'Alarm register write failed'),
    0xEF: ('FAULT', 'ALARM_READBACK_FAILED', 'Alarm register readback failed'),
    0xF0: ('FAULT', 'ALARM_VERIFY_MISMATCH', 'Alarm write/readback mismatch'),
    0xF1: ('FAULT', 'ALARM_FLAG_CLEAR_FAILED', 'Previous alarm flag could not be cleared'),
    0xF2: ('FAULT', 'WRITE_VERIFY_MISMATCH', 'Calendar write/readback mismatch'),
}

# RTC Communication Fault Codes
RTC_COMMUNICATION_FAULT_CODES = {
    0xE1, 0xE2, 0xE5, 0xE6, 0xE7, 0xE8, 0xE9, 0xEA
}

